### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by fuckwbored** [mesquidar/adbsploit#10]
Hey! I used shodan to find target device. When i try to connect i have an error:
connection refused

Can you help me please?

**Comment by Omicron166yt** [comment]
try to connect using shell adb, if it also doesn't work then the problem is that it is not an adb port

**Comment by Temuxuser2021** [comment]
Enter the phone IP address to connect
 └──> adbsploit(connect) > ............
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbutils-0.11.0-py3.10.egg/adbutils/__init__.py", line 103, in _safe_connect
    return self._create_socket()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbutils-0.11.0-py3.10.egg/adbutils/__init__.py", line 95, in _create_socket
    s.connect((adb_host, adb_port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/adbsploit", line 33, in <module>
    sys.exit(load_entry_point('adbsploit==0.1', 'console_scripts', 'adbsploit')())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbsploit-0.1-py3.10.egg/adbsploit/adbsploit.py", line 37, in main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbsploit-0.1-py3.10.egg/adbsploit/adbsploit.py", line 45, in main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbsploit-0.1-py3.10.egg/adbsploit/adbsploit.py", line 235, in connect
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbutils-0.11.0-py3.10.egg/adbutils/__init__.py", line 263, in connect
    with self._connect(timeout=timeout) as c:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbutils-0.11.0-py3.10.egg/adbutils/__init__.py", line 189, in _connect
    _conn = _AdbStreamConnection(self.__host, self.__port)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbutils-0.11.0-py3.10.egg/adbutils/__init__.py", line 88, in __init__
    self.__conn = self._safe_connect()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbutils-0.11.0-py3.10.egg/adbutils/__init__.py", line 106, in _safe_connect
    return self._create_socket()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/adbutils-0.11.0-py3.10.egg/adbutils/__init__.py", line 95, in _create_socket
    s.connect((adb_host, adb_port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by Omicron166** [comment]
Either you don't have access to the device, or the port is closed

**Comment by ChillVibesMushroom** [comment]
> Hey! I used shodan to find target device. When i try to connect i have an error: connection refused
> 
> Can you help me please?

Do you still need help some things to try are

pinging the device

looking into adb --help shows you the list of commands that you can use in order to set yourself up for success.

**Comment by ChillVibesMushroom** [comment]
> Either you don't have access to the device, or the port is closed

Yo.  If I am using adb over lan and I can connect via my ipv4:5555 by using adbtools why would I not be able to connect with the tool?. 

How would I go about being able to connect using the tool. I know that I can disconnect from my ipv4:5555 and the adbridge will still send a signal So. that I can reconnect anytime, but for some reason I get connection refused from the tool. hahaha.
