### ISSUE TITLE
Not working on Raspberry Pi 3B+/4 :'(

### ISSUE THREAD

**Issue by up2smoke** [mesquidar/adbsploit#7]
Not possible to Install it on Raspi OS (Raspberry Pi)..
Install ends with the follow Error

`pi@raspberrypi:~/adbsploit $ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
  File "build/bdist.linux-armv7l/egg/setuptools/__init__.py", line 21, in <module>
  File "build/bdist.linux-armv7l/egg/setuptools/version.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setuptools-49.2.1-py2.7.egg/pkg_resources/__init__.py", line 1380
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax`

**Comment by Piyush328** [comment]
https://github.com/mesquidar/adbsploit.git

**Comment by Omicron166yt** [comment]
`File "/usr/local/lib/python2.7/dist-packages/setuptools-49.2.1-py2.7.egg/pkg_resources/__init__.py"`
You are using python 2.7, this program is only compatible with python3.x

You can install it with the package python3
